version: '2.4'

services:
  vault:
    image: vault:1.13.3
    restart: always
    volumes:
      - ./vault.json:/vault/config/vault.json
      - ./data/vault-data:/vault/file
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_API_ADDR}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    ports:
      - 8200:8200
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://127.0.0.1:8200/v1/sys/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vault
    networks:
      - network

networks:
  network:
    driver: bridge
    name: kwings_network
